import type {Metadata} from "next";
import {Inter, JetBrains_Mono} from "next/font/google";
import {ViewTransitions} from 'next-view-transitions'
import "./globals.css";
import {ReactNode} from "react";
import {BlurHeader} from "@/components/Header";
import Layout from "@/Layout";
import {SidebarProvider, SidebarTrigger} from "@/components/ui/sidebar";
import {AppSidebar} from "@/components/app-sidebar";

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
});

const jetBrainsMono = JetBrains_Mono({
    variable: "--font-jetbrains-mono",
    subsets: ["latin"],
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: ReactNode;
}>) {
    return (
        <ViewTransitions>
            <html lang="en">
            <body
                className={`${inter.variable} ${jetBrainsMono.variable} antialiased`}
            >
            <SidebarProvider>
                <AppSidebar/>
                <Layout>
                    <BlurHeader/>
                    <main className="pt-14">
                        {children}
                    </main>
                </Layout>
            </SidebarProvider>
            </body>
            </html>
        </ViewTransitions>
    );
}
